"""
Django settings for beltechprinting project.

Generated by 'django-admin startproject' using Django 4.2.26.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/

"""

import mimetypes
mimetypes.add_type("image/webp", ".webp", True)
mimetypes.add_type("image/png", ".png", True)

from pathlib import Path
import os
import environ

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# This points to the .env file in your root folder
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = env('DEBUG')

# ALLOWED_HOSTS = ['*']
ALLOWED_HOSTS = ['developer7.pythonanywhere.com', '127.0.0.1', 'localhost']


DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'beltechApp',
]

LOGIN_URL = '/admin/login/'

THIRD_PARTY_APPS = [
    'crispy_forms',
    'crispy_bootstrap5',
    'django_ckeditor_5', # Uncommented this for you
]

LOCAL_APPS = [
    'beltechApp',       # Root app
    # 'accounts',   # Organized apps
    # 'core',
    # 'services',
    # 'orders',
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

# CKEditor 5 Configuration
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': ['heading', '|', 'bold', 'italic', 'link', 'bulletedList', 'numberedList', 'blockQuote', 'imageUpload', ],
    },
}

AUTH_USER_MODEL = 'beltechApp.CustomUser'

# X_FRAME_OPTIONS = "SAMEORIGIN"


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # 'beltechApp.middleware.AllowYouTubeEmbeddingMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'beltechprinting.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'beltechApp.context_processors.site_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'beltechprinting.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATICFILES_DIRS = [
    BASE_DIR / 'beltechApp' / 'static',  # make sure this points to your app static folder
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')




# Media files (Customer PDF uploads/Designs)
MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



# Use the environment variable if it exists, otherwise use the insecure local one
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-$v19c0)0w$#o6)!68geyuipgib-#(hs2m-^8m7c=4=nrtx(5=r')

# DEBUG should be False on Render
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['Developer7.pythonanywhere.com', '127.0.0.1', 'localhost']


# new area
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.zoho.com'  # Usually starts with 'mail.'
# EMAIL_PORT = 465                    # 465 is for SSL, 587 is for TLS
# EMAIL_USE_SSL = True                # Set to True if using port 465
# EMAIL_USE_TLS = False               # Set to True if using port 587
# EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
# EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
# DEFAULT_FROM_EMAIL = 'Beltech Printing Press <info@beltech.com.ng>'
# # end new

# # Site Domain for Newsletters/Links
# SITE_DOMAIN = os.environ.get('SITE_DOMAIN', 'http://127.0.0.1:8000')


# DEFAULT_FROM_EMAIL = 'Beltech Printing Press <info@beltech.com.ng>'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

# new area
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.zoho.com'

# For Zoho, port 587 with TLS is generally more recommended and widely supported.
# If you explicitly want to use 465 with SSL, keep EMAIL_PORT = 465 and EMAIL_USE_SSL = True.
# However, for most modern setups, 587 with TLS is the standard.
EMAIL_PORT = 587                    # 587 is typically for TLS
EMAIL_USE_SSL = False               # Set to False if using port 587
EMAIL_USE_TLS = True                # Set to True if using port 587 (recommended)

# Ensure these are correctly loaded as environment variables in PythonAnywhere's "Web" tab.
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')

# This is the email address that appears as the sender.
# It should match your EMAIL_HOST_USER for authentication with Zoho.
DEFAULT_FROM_EMAIL = 'info@beltech.com.ng'

# You can also set a SERVER_EMAIL for error notifications if needed
# SERVER_EMAIL = 'errors@beltech.com.ng' # Optional, for Django error reporting

# end new

# Site Domain for Newsletters/Links
SITE_DOMAIN = os.environ.get('SITE_DOMAIN', 'http://127.0.0.1:8000')

# This line was duplicated, no need for it twice
# DEFAULT_FROM_EMAIL = 'Beltech Printing Press <info@beltech.com.ng>'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# SITE_DOMAIN = env('SITE_DOMAIN', default='127.0.0.1:8000')
# print(f"DEBUG: Media Root is {MEDIA_ROOT}")
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

LOGIN_URL = '/admin/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'