# Generated by Django 4.2.27 on 2025-12-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltechApp', '0002_rename_discription_carousel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='image2',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
