# Generated by Django 4.2.27 on 2025-12-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltechApp', '0005_homepage_service_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage_about_area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media/')),
                ('icon1', models.CharField(max_length=50)),
                ('icon2', models.CharField(max_length=50)),
                ('image1', models.ImageField(upload_to='media/')),
                ('image2', models.ImageField(upload_to='media/')),
                ('image3', models.ImageField(upload_to='media/')),
                ('image_expert', models.ImageField(upload_to='media/')),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
    ]
