# Generated by Django 4.2.27 on 2025-12-30 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beltechApp', '0006_homepage_about_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage_about_area',
            name='image',
        ),
    ]
