# Generated by Django 4.2.27 on 2025-12-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltechApp', '0007_remove_homepage_about_area_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage_about_area',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
