# Generated by Django 4.2.27 on 2025-12-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltechApp', '0008_homepage_about_area_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage_about_area',
            name='description1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepage_about_area',
            name='description2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
