# Generated by Django 4.2.27 on 2025-12-30 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltechApp', '0009_homepage_about_area_description1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage_about_area',
            name='icon1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage_about_area',
            name='icon2',
            field=models.CharField(max_length=100),
        ),
    ]
