# Generated by Django 4.2.27 on 2025-12-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltechApp', '0010_alter_homepage_about_area_icon1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='services-category/'),
        ),
        migrations.AlterField(
            model_name='printingservice',
            name='image',
            field=models.ImageField(upload_to='services/'),
        ),
    ]
