# Generated by Django 4.2.27 on 2025-12-31 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltechApp', '0011_remove_category_description_category_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='printingHomePageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='services/')),
            ],
        ),
    ]
