# Generated by Django 4.2.27 on 2025-12-31 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beltechApp', '0012_printinghomepageimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printinghomepageimage',
            old_name='image1',
            new_name='image',
        ),
    ]
