# Generated by Django 4.2.27 on 2025-12-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltechApp', '0013_rename_image1_printinghomepageimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='printingservice',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
