# Generated by Django 4.2.27 on 2025-12-31 13:56

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('beltechApp', '0014_printingservice_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Already_done_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
                ('image', models.ImageField(upload_to='services/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readymade', to='beltechApp.category')),
            ],
        ),
    ]
