# Generated by Django 4.2.27 on 2025-12-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltechApp', '0015_already_done_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='already_done_project',
            name='image',
            field=models.ImageField(upload_to='projects/'),
        ),
    ]
