# Generated by Django 4.2.27 on 2025-12-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltechApp', '0016_alter_already_done_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='printingservice',
            name='is_latest',
            field=models.BooleanField(default=False),
        ),
    ]
