# Generated by Django 4.2.27 on 2025-12-31 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beltechApp', '0017_printingservice_is_latest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('main_image', models.ImageField(help_text='Featured image at the top', upload_to='blog/main/')),
                ('secondary_image', models.ImageField(blank=True, help_text='Image for the middle of the article', null=True, upload_to='blog/secondary/')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Body Content')),
                ('quote_text', models.TextField(blank=True, help_text='Special highlighted quote in the article')),
                ('quote_author', models.CharField(blank=True, help_text='Author of the quote', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
