# Generated by Django 4.2.27 on 2026-01-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltechApp', '0019_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('main_image', models.ImageField(help_text='Logo image', upload_to='logo/')),
            ],
        ),
    ]
