# Generated by Django 4.2.27 on 2026-01-01 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beltechApp', '0021_blog_category_blogpost_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog_category',
            options={'verbose_name_plural': 'Blog category'},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blopPost', to='beltechApp.blog_category'),
        ),
    ]
