# Generated by Django 4.2.27 on 2026-01-03 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beltechApp', '0026_blogcomment_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='beltechApp.blogpost'),
        ),
    ]
