# Generated by Django 4.2.27 on 2026-01-03 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beltechApp', '0027_blogpost_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='parent',
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='beltechApp.blogcomment'),
        ),
    ]
