# Generated by Django 4.2.27 on 2026-01-06 20:04

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('beltechApp', '0028_remove_blogpost_parent_blogcomment_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
                ('image', models.ImageField(upload_to='services/')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
