# Generated by Django 4.2.27 on 2026-01-06 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beltechApp', '0029_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrintingService',
            new_name='Products',
        ),
    ]
