# Generated by Django 4.2.27 on 2026-01-07 04:44

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('beltechApp', '0030_rename_printingservice_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Body Content')),
            ],
        ),
    ]
