# Generated by Django 4.2.27 on 2026-01-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltechApp', '0031_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='How We Bring Your Ideas To Life', max_length=200)),
                ('sub_title', models.CharField(default='WATCH OUR PROCESS', max_length=100)),
                ('youtube_url', models.URLField(help_text='Enter the full YouTube URL (e.g., https://www.youtube.com/watch?v=go7QYaQR494)')),
            ],
            options={
                'verbose_name': 'Process Video',
                'verbose_name_plural': 'Process Video',
            },
        ),
    ]
