# Generated by Django 4.2.27 on 2026-01-07 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beltechApp', '0032_processvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='services/')),
                ('role', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='processvideo',
            options={'verbose_name': 'Process Video', 'verbose_name_plural': 'Process Videos'},
        ),
        migrations.AlterField(
            model_name='processvideo',
            name='youtube_url',
            field=models.URLField(help_text='Paste a YouTube video URL (not playlist or channel)'),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Client or customer name', max_length=100)),
                ('message', models.TextField(help_text='Client testimonial message')),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Rating from 1 to 5')),
                ('is_active', models.BooleanField(default=True, help_text='Show or hide this testimonial on the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logo_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beltechApp.logo')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-created_at'],
            },
        ),
    ]
