# Generated by Django 4.2.27 on 2026-01-07 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltechApp', '0033_team_alter_processvideo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='stars',
            field=models.IntegerField(default=5, help_text='Rate from 1 to 5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
