# Generated by Django 4.2.27 on 2026-01-07 21:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltechApp', '0034_testimonial_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='stars',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='main_image',
            field=models.ImageField(help_text='Featured image at the top', null=True, upload_to='blog/main/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(default=5, help_text='Rate from 1 to 5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
