# Generated by Django 4.2.27 on 2026-01-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltechApp', '0035_remove_testimonial_stars_testimonial_main_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Featured image at the top', null=True, upload_to='blog/main/'),
        ),
    ]
