# Generated by Django 4.2.27 on 2026-01-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltechApp', '0036_alter_testimonial_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='is_approve',
            field=models.BooleanField(default=True, help_text='Admin approve or decline the testimony'),
        ),
    ]
