# Generated by Django 4.2.27 on 2026-01-08 20:43

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('beltechApp', '0037_testimonial_is_approve'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(help_text="User's email address", max_length=254)),
                ('website', models.URLField(blank=True, help_text="User's website (optional)", null=True)),
                ('message', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-date'],
            },
        ),
    ]
