# Generated by Django 4.2.27 on 2026-01-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltechApp', '0038_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='website',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(help_text='e.g. +234 800 000 0000', max_length=20, null=True),
        ),
    ]
