# Generated by Django 4.2.27 on 2026-01-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltechApp', '0039_remove_contact_website_contact_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Beltech Printing', max_length=100)),
                ('address', models.CharField(help_text='e.g. Shop No. A 6, Musty Global Plaza', max_length=255)),
                ('street', models.CharField(help_text='e.g. Circular Road', max_length=255)),
                ('landmark', models.CharField(help_text='e.g. Opposite Nanne and Boi', max_length=255)),
                ('city_state', models.CharField(default='Maiduguri, Borno State', max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('google_maps_link', models.TextField(help_text="Paste the iframe 'src' link here")),
            ],
            options={
                'verbose_name_plural': 'Company Information',
            },
        ),
    ]
