# Generated by Django 4.2.27 on 2026-01-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltechApp', '0040_companyinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_read',
            field=models.BooleanField(default=True, help_text='This indicate that you have read this message'),
        ),
    ]
