# Generated by Django 4.2.27 on 2026-01-09 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beltechApp', '0041_contact_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='image2',
        ),
    ]
