# Generated by Django 4.2.27 on 2026-01-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltechApp', '0042_remove_carousel_image2'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Beltech Printing', max_length=100)),
                ('whatsapp_number', models.CharField(help_text='Enter number with country code, no plus sign (e.g., 2348030000000)', max_length=15)),
                ('business_address', models.TextField(default='Musty Global Plaza, Maiduguri')),
                ('contact_email', models.EmailField(default='info@beltech.com.ng', max_length=254)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='printinghomepageimage',
            options={'verbose_name': 'Breadcrumb images'},
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
