# Generated by Django 4.2.27 on 2026-01-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltechApp', '0043_sitesetting_alter_printinghomepageimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(upload_to='carousel/'),
        ),
    ]
