# Generated by Django 4.2.27 on 2026-01-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltechApp', '0045_customuser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='homepage_about_area',
            name='image',
            field=models.ImageField(null=True, upload_to='about_image/'),
        ),
        migrations.AlterField(
            model_name='homepage_about_area',
            name='image1',
            field=models.ImageField(upload_to='about_image/'),
        ),
        migrations.AlterField(
            model_name='homepage_about_area',
            name='image2',
            field=models.ImageField(upload_to='about_image/'),
        ),
        migrations.AlterField(
            model_name='homepage_about_area',
            name='image3',
            field=models.ImageField(upload_to='about_image/'),
        ),
        migrations.AlterField(
            model_name='homepage_about_area',
            name='image_expert',
            field=models.ImageField(upload_to='about_image/'),
        ),
        migrations.AlterField(
            model_name='homepage_service_area',
            name='image',
            field=models.ImageField(upload_to='service/'),
        ),
    ]
