# Generated by Django 4.2.27 on 2026-01-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltechApp', '0047_newsletter_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='unit',
            field=models.CharField(default='Pieces', max_length=50),
        ),
    ]
