# Generated by Django 4.2.27 on 2026-01-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltechApp', '0049_alter_products_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='about',
            field=models.CharField(default='Beltech Printing & ICT Hub (commonly referred to as Beltech Printing Press) is a multi-service business that bridges the gap between traditional high-quality printing and modern digital technology.', max_length=200),
        ),
    ]
