# Generated by Django 4.2.27 on 2026-01-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltechApp', '0050_companyinformation_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage_about_area',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='homepage_about_area',
            name='description1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='homepage_about_area',
            name='description2',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
