# Generated by Django 4.2.27 on 2026-01-17 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beltechApp', '0051_alter_homepage_about_area_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Account Management Staff'},
        ),
    ]
