# Generated by Django 4.2.27 on 2026-01-22 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beltechApp', '0052_alter_customuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialHandlesTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_link_url', models.URLField(max_length=500)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beltechApp.team')),
            ],
            options={
                'verbose_name': 'Teams social handle',
            },
        ),
        migrations.CreateModel(
            name='SocialHandlesCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_link_url', models.URLField(max_length=500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beltechApp.companyinformation')),
            ],
            options={
                'verbose_name': 'Teams social handle',
            },
        ),
    ]
