# Generated by Django 4.2.27 on 2026-01-22 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beltechApp', '0053_socialhandlesteam_socialhandlescompany'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialhandlescompany',
            options={'verbose_name': 'SocialHandelCompany'},
        ),
        migrations.AlterModelOptions(
            name='socialhandlesteam',
            options={'verbose_name': 'SocialHandelTeams'},
        ),
    ]
